import {Inter} from '@next/font/google'
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: "Blog Website",
  description: "Generated by create next app",
};

const interFont = Inter({ subsets: ["latin"] })

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={interFont.className}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
